#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

### BEGIN INIT INFO
# Provides:          perl-spm
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Short-Description: start and stop Perl SCGI Process Manager perl-spm
# Description:       perl-spm SCGI Process Manager for perl 
### END INIT INFO


pm_file=(/path/to/perl-spm/perl-spm.pl)
echo "Perl-SPM File: $pm_file"

case "$1" in
  start)
        echo "Starting Perl-SPM .."
        spm_start=$($pm_file)
	echo $spm_start
        ;;
  stop)
	pid=$(cat /tmp/perl-spm.pid)
        echo "Stopping Perl-SPM with PID $pid .. "
        spm_stop=$(/bin/kill $pid)
	echo $spm_stop
        ;;
  restart)
	pid=$(cat /tmp/perl-spm.pid)
        echo "Stopping Perl-SPM with PID $pid .. "
        spm_stop=$(/bin/kill $pid)
	echo $spm_stop

        sleep 1
        
        echo "Re-Starting Perl-SPM .."
        spm_start=$(/etc/init.d/perl-spm start)
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
